import Menu from "./Components/Menu";
import Footer from "./Components/Footer";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Menu/>
        {children}
       <Footer/>
        </body>
    </html>
  )
}
